[toolchain]
channel = "nightly"
targets = [ "x86_64-apple-ios", "aarch64-apple-ios", "aarch64-apple-ios-sim", "aarch64-linux-android", "x86_64-linux-android", "armv7-linux-androideabi", "i686-linux-android" ]